/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './index.html',
    './index.tsx',
    './App.tsx',
    './components/**/*.{js,ts,jsx,tsx}',
    './mobile/**/*.{js,ts,jsx,tsx}',
    './data/**/*.{js,ts,jsx,tsx}',
    './context/**/*.{js,ts,jsx,tsx}',
    './hooks/**/*.{js,ts,jsx,tsx}',
    './utils/**/*.{js,ts,jsx,tsx}',
    './services/**/*.{js,ts,jsx,tsx}',
  ],
  safelist: [
    // WorkoutLogScreen set table dynamic column classes
    'grid-cols-[36px_repeat(1,_1fr)_40px_48px]',
    'grid-cols-[36px_repeat(2,_1fr)_40px_48px]',
    'grid-cols-[36px_repeat(3,_1fr)_40px_48px]',
    'grid-cols-[36px_repeat(4,_1fr)_40px_48px]',
    'grid-cols-[36px_repeat(5,_1fr)_40px_48px]',
    // GROUP_COLORS bg
    'bg-blue-500',
    'bg-pink-500',
    'bg-lime-500',
    'bg-orange-500',
    'bg-purple-500',
    'bg-yellow-400',
    // GROUP_COLORS border
    'border-blue-500',
    'border-pink-500',
    'border-lime-500',
    'border-orange-500',
    'border-purple-500',
    'border-yellow-400',
    // GROUP_COLORS lightBg
    'bg-blue-50',
    'dark:bg-blue-900/20',
    'bg-pink-50',
    'dark:bg-pink-900/20',
    'bg-lime-50',
    'dark:bg-lime-900/20',
    'bg-orange-50',
    'dark:bg-orange-900/20',
    'bg-purple-50',
    'dark:bg-purple-900/20',
    'bg-yellow-50',
    'dark:bg-yellow-900/20',
    // Dynamic groupColor .replace('bg-', 'border-')
    'border-blue-500',
    'border-pink-500',
    'border-lime-500',
    'border-orange-500',
    'border-purple-500',
    'border-yellow-400',
    // Dynamic groupColor .replace('bg-', 'border-l-')
    'border-l-blue-500',
    'border-l-pink-500',
    'border-l-lime-500',
    'border-l-orange-500',
    'border-l-purple-500',
    'border-l-yellow-400',
    // Dynamic groupColor .replace('bg-', 'text-')
    'text-blue-500',
    'text-pink-500',
    'text-lime-500',
    'text-orange-500',
    'text-purple-500',
    'text-yellow-400',
    // getTagColor classes
    'bg-red-200',
    'text-red-800',
    'dark:bg-red-900/50',
    'dark:text-red-200',
    'bg-blue-100',
    'text-blue-800',
    'dark:bg-blue-900/50',
    'dark:text-blue-200',
    'bg-teal-100',
    'text-teal-900',
    'dark:bg-teal-900/50',
    'dark:text-teal-200',
    'bg-purple-100',
    'text-purple-900',
    'dark:bg-purple-900/50',
    'dark:text-purple-200',
    'bg-yellow-200',
    'text-yellow-800',
    'dark:bg-yellow-900/50',
    'dark:text-yellow-200',
    'bg-pink-100',
    'text-pink-800',
    'dark:bg-pink-900/50',
    'dark:text-pink-200',
    'bg-orange-500',
    'text-white',
    'bg-gray-500',
    // Timer modes & status colors
    'bg-work',
    'text-work',
    'bg-work/10',
    'dark:bg-work/20',
    'border-work/30',
    'border-work/40',
    'bg-rest',
    'border-rest',
    'border-rest/40',
    'bg-record',
    'bg-danger',
    'bg-blue-600',
    'border-blue-400',
    'bg-red-600',
    'border-red-400',
    'bg-pink-600',
    'border-pink-400',
    'bg-pink-700',
    'bg-purple-600',
    'border-purple-400',
    'bg-purple-700',
    'bg-indigo-600',
    'border-indigo-400',
    'bg-indigo-700',
    'bg-green-600',
    'border-green-400',
    'bg-green-700',
    'bg-gray-600',
    'border-gray-400',
    'bg-slate-800',
    'border-slate-600',
    'bg-slate-700',
    // RPE scale colors
    'bg-green-100',
    'text-green-700',
    'dark:bg-green-900/30',
    'dark:text-green-300',
    'bg-yellow-100',
    'text-yellow-700',
    'dark:bg-yellow-900/30',
    'dark:text-yellow-300',
    'bg-red-100',
    'text-red-700',
    'dark:bg-red-900/30',
    'dark:text-red-300',
  ],
  theme: {
    extend: {
      colors: {
        'primary': 'var(--color-primary, #14b8a6)',
        'work': '#f97316',
        'rest': '#14b8a6',
        'record': '#f59e0b',
        'danger': '#dc2626',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        logo: ['Satisfy', 'cursive'],
        handwriting: ['Caveat', 'cursive'],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'Liberation Mono', 'Courier New', 'monospace']
      },
      animation: {
        'fade-in': 'fadeIn 0.15s ease-out forwards',
        'fade-out': 'fadeOut 0.15s ease-out forwards',
        'pulse-loader': 'pulseLoader 1s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'pulse-bg-light': 'pulse-bg-light-keyframes 2.5s ease-in-out infinite',
        'pulse-bg-medium': 'pulse-bg-medium-keyframes 1.5s ease-in-out infinite',
        'pulse-bg-intense': 'pulse-bg-intense-keyframes 0.8s ease-in-out infinite',
        'pulse-inset-light': 'pulse-inset-light-keyframes 2.5s ease-in-out infinite',
        'pulse-inset-medium': 'pulse-inset-medium-keyframes 1.5s ease-in-out infinite',
        'pulse-inset-intense': 'pulse-inset-intense-keyframes 0.8s ease-in-out infinite',
        'slide-in-left': 'slideInLeft 0.35s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'slide-in-right': 'slideInRight 0.35s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'fade-in-banner': 'fadeInBanner 0.35s ease-out forwards',
        'fade-in-out': 'fade-in-out 3s ease-in-out forwards',
        'word-cloud-fade-in': 'word-cloud-fade-in 0.5s ease-out forwards',
        'zoom-fade-in': 'zoomFadeIn 0.2s ease-out forwards',
        'slide-in-from-left': 'slideInFromLeft 0.25s ease-out forwards',
        'slide-out-to-right': 'slideOutToRight 0.25s ease-in forwards',
        'pulse-hyrox-bg': 'pulse-hyrox-bg-keyframes 10s ease-in-out infinite',
        'pulse-border': 'pulse-border-keyframes 1.5s ease-in-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        fadeOut: {
          'from': { opacity: '1' },
          'to': { opacity: '0' },
        },
        pulseLoader: {
          '0%': { transform: 'scale(.1)', opacity: '1' },
          '70%': { transform: 'scale(1)', opacity: '0.7' },
          '100%': { opacity: '0' },
        },
        zoomFadeIn: {
          'from': { opacity: '0', transform: 'scale(0.95)' },
          'to': { opacity: '1', transform: 'scale(1)' },
        },
        slideInFromLeft: {
          'from': { opacity: '0', transform: 'translateX(-100%)' },
          'to': { opacity: '1', transform: 'translateX(0)' },
        },
        slideOutToRight: {
          'from': { opacity: '1', transform: 'translateX(0)' },
          'to': { opacity: '0', transform: 'translateX(100%)' },
        }
      }
    }
  },
  plugins: [],
};
