import { Workout, TimerMode } from '../types';

export interface BoostWorkout extends Workout {
  difficulty: 'enkel' | 'avancerad';
}

// Per user request, the pre-defined workouts are removed.
// Boost workouts will now be generated by the AI.
export const boostWorkouts: BoostWorkout[] = [];
